name: Test

on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {spark: 2.3.2, scala: 2.11}
          - {spark: 2.4.8, scala: 2.11}
          - {spark: 2.4.8, scala: 2.12}
          - {spark: 3.2.4, scala: 2.12}
          - {spark: 3.2.4, scala: 2.13}
          - {spark: 3.3.2, scala: 2.12}
          - {spark: 3.3.2, scala: 2.13}
          - {spark: 3.4.1, scala: 2.12}
          - {spark: 3.4.1, scala: 2.13}
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        cache: maven
        check-latest: false
    - name: Test with Maven
      run: |
        export TERA_SORT_SIZE=1g
        build/mvn clean test -Dspark.version=${{ matrix.spark }} -Pscala-${{ matrix.scala }}
    - name: Upload test log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: spark-${{ matrix.spark }}-scala-${{ matrix.scala }}-unit-test-log
        path: |
          **/target/unit-tests.log
