#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    if: ${{ startsWith(github.repository, 'pan3793/') }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { spark: 2.4.8, scala: 2.11 }
          - { spark: 3.3.2, scala: 2.12 }
          - { spark: 3.4.1, scala: 2.13 }
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
          check-latest: false
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Publish Release
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
        run: |
          build/mvn clean deploy -DskipTests -s build/release/ossrh-settings.xml \
            -Prelease \
            -Dspark.version=${{ matrix.spark }} \
            -Pscala-${{ matrix.scala }}

  create-github-release:
    if: ${{ startsWith(github.repository, 'pan3793/') }}
    runs-on: ubuntu-22.04
    needs: publish-release
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
